---
title: "Lab 03 - Nobel laureates"
author: "Heather Hawkins"
date: "01/23/23"
output: github_document
---

### Load packages and data

```{r load-packages, message=FALSE}
library(tidyverse) 
```

```{r load-data, message=FALSE}
nobel <- read_csv("data/nobel.csv")
```

## Exercises

### Exercise 1

```{r data, message=FALSE}
nobel <- read_csv("data/nobel.csv")
dim(nobel)
#to specify columns and rows
```

26 variables and 935 observations, each observation is a Noble Laureate

### Exercise 2


```{r nobel_living}
nobel_living <- nobel %>%
  filter(!is.na(country), gender!="org",is.na(died_date),)

dim(nobel_living)
```

Got it! ☺️

```{r USA}
living_during_prize <- nobel_living %>%
  mutate(
    living_during_prize = if_else(country == "USA", "USA", "Other")
  )
```

```{R Sciences}
nobel_living_science <- living_during_prize %>%
  filter(category %in% c("Physics", "Medicine", "Chemistry", "Economics"))

dim(nobel_living)
```

### Exercise 3

```{R prize-us}
ggplot(nobel_living_science, aes(x = category, fill = living_during_prize)) +
  geom_bar(position = "stack") +
  coord_flip() + facet_wrap(~living_during_prize)+ labs (x= "Category of Science", y= "Number of Nobel Laureates" ) + labs(fill="Country During Prize") 
```

### Exercise 4
```{r USA_born}
nobel_living_science_born <- nobel_living_science %>%
  mutate(
    born_country_us = if_else(country == "USA", "USA", "Other")
  )

dim(nobel_living_science_born)

```

```{R prize-born}
ggplot(nobel_living_science_born, aes(x = born_country_us)) +
  geom_bar(position = "stack") +
  coord_flip() + facet_wrap(~category)+ labs (x= "Country of Birth", y= "Number of Nobel Laureates" ) + labs(fill="Category of Science") 

summary_born <- nobel_living_science_born %>%
  count(category,born_country_us, country, sort = TRUE) 

```

```{r nobel_living_NA}
summary_born <- nobel_living_science_born %>%
  count(category,born_country_us) 

```
```
### Exercise 5

...

### Exercise 6

...
